export const UPDATE_LISTENED_SECONDS = 'UPDATE_LISTENED_SECONDS';
export const UPDATE_LISTENED_MINUTES = 'UPDATE_LISTENED_MINUTES';
export const UPDATE_LISTENED_HOURS = 'UPDATE_LISTENED_HOURS';
export const UPDATE_LISTENED_PERCENT = 'UPDATE_LISTENED_PERCENT';

export const UPDATE_TOTAL_SECONDS = 'UPDATE_TOTAL_SECONDS';
export const UPDATE_TOTAL_MINUTES = 'UPDATE_TOTAL_MINUTES';
export const UPDATE_TOTAL_HOURS = 'UPDATE_TOTAL_HOURS';

export const UPDATE_INTRO_SECONDS = 'UPDATE_INTRO_SECONDS';
export const UPDATE_INTRO_MINUTES = 'UPDATE_INTRO_MINUTES';

export const UPDATE_OUTRO_SECONDS = 'UPDATE_OUTRO_SECONDS';
export const UPDATE_OUTRO_MINUTES = 'UPDATE_OUTRO_MINUTES';